#!/usr/bin/env bash
# Install Nginx and hello world page.

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
sudo service nginx reload
