#!/usr/bin/env bash
# Process and PID file
echo $? > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; pkill -f 100-process_and_pid_file' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
