#!/usr/bin/env bash
# Displays "Best School" 10 times but on 4 - 8 using good and bad luck
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))	
done
