#!/usr/bin/env bash
# check if school file exists
if [ -e  "school" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
	exit 1
fi
# checks emptiness
if [ ! -s "school" ]
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
# checks if is a regular file
if [ -f "school" ]
then
	echo "school is a regular file"
fi
